# Generated by Django 3.2 on 2021-04-30 13:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='joboffer',
            name='salary',
            field=models.TextField(),
        ),
    ]
